banking_dbt:
  target: dev

  outputs:
    dev:
      type: duckdb
      path: "dev.duckdb"
      threads: 4
      settings:
        s3_endpoint: "localhost:9000"
        s3_use_ssl: false
        s3_url_style: "path"
        s3_region: "us-east-1"
        s3_access_key_id: "banking"
        s3_secret_access_key: "banking_dev"